---
# tasks file for vmwaretools/Debian

- name: Installing Open VMware Tools (open-vm-tools)
  apt: name=open-vm-tools state=present

- template:
    src: open-vm-tools.service.j2
    dest: /lib/systemd/system/open-vm-tools.service

- name: Create symbolic link for vmwaretools
  file:
    src: /etc/dhcp
    dest: /etc/dhcp3
    state: link
