---
# tasks file for vmwaretools/RedHat

- name: Get repository package version if vmwaretools_repo_version is undefined
  shell: curl {{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/index.html | sed -n "s/.*vmware-tools-repo-RHEL{{ ansible_distribution_major_version }}-\(.*\)\.el{{ ansible_distribution_major_version }}\.{{ ansible_architecture }}\.rpm.*/\1/p"
  register: vmwaretools_repo_version2
  when: vmwaretools_repo_version is undefined and ansible_distribution_major_version|int <= 6
  changed_when: false

- name: Get details about repository package version if vmwaretools_repo_version is undefined
  set_fact:
    vmwaretools_repo_version: "{{ vmwaretools_repo_version2.stdout }}"
  when: vmwaretools_repo_version is undefined and not( vmwaretools_repo_version2.stdout is undefined or vmwaretools_repo_version2.stdout is none or vmwaretools_repo_version2.stdout | trim == '' )

- name: Install vmware-tools repository
  yum: name={{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/vmware-tools-repo-RHEL{{ ansible_distribution_major_version }}-{{ vmwaretools_repo_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm
  when: ansible_distribution_major_version|int <= 6

- name: Disable GPG check for vmware-osps repository (1/2)
  ini_file:
    path: /etc/yum.repos.d/vmware-osps.repo
    section: vmware-tools-collection
    option: gpgcheck
    value: 0
    backup: yes
  when: ansible_distribution_major_version|int <= 6

- name: Disable GPG check for vmware-osps repository (2/2)
  ini_file:
    path: /etc/yum.repos.d/vmware-osps.repo
    section: vmware-tools-collection
    option: repo_gpgcheck
    value: 0
    backup: yes
  when: ansible_distribution_major_version|int <= 6

- name: Remove the open-vm-tools if they are installed not to block vmware-tools installation
  yum: name=open-vm-tools state=absent
  when: ansible_distribution_major_version|int <= 6

- name: Install vmware-tools
  yum: name={{ item }}
  with_items:
    - vmware-tools-esx-nox
    - vmware-tools-esx-kmods
  when: ansible_distribution_major_version|int <= 6

# http://partnerweb.vmware.com/GOSIG/RHEL_7.html
- name: Installing Open VMware Tools (open-vm-tools) for CentOS/RHEL 7 and higher
  yum: name=open-vm-tools state=installed
  when: ansible_distribution_major_version|int >= 7

- name: Start vmtoolsd and enable vmtoolsd to start during boot for CentOS/RHEL 7 and higher
  service: name=vmtoolsd state=started enabled=yes
  failed_when: false
  when: ansible_distribution_major_version|int >= 7

- name: Start and enable vmware-tools-services during boot for CentOS/RHEL 6 and higher
  service: name=vmware-tools-services state=started enabled=yes
  failed_when: false
  when: ansible_distribution_major_version|int <= 6
